apiVersion: v1
kind: Service
metadata:
  name: {{ include "project-commander.masterSlaveServiceName" . }}
  labels:
    {{- include "project-commander.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: {{ .Values.controlPlane.slaveService.type }}
  selector:
    {{- include "project-commander.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: slave
      port: {{ .Values.controlPlane.slaveService.port }}
      targetPort: slave
      protocol: TCP
      {{- if and .Values.controlPlane.slaveService.nodePort (or (eq .Values.controlPlane.slaveService.type "NodePort") (eq .Values.controlPlane.slaveService.type "LoadBalancer")) }}
      nodePort: {{ .Values.controlPlane.slaveService.nodePort }}
      {{- end }}
